services:

  frontend:
    build:
      context: FrontEnd
      target: dev-envs
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - react-express
    depends_on:
      - backend
    expose: 
      - 3000

  backend:
    restart: always
    build:
      context: BackEnd
      target: dev-envs
    ports:
      - 5173:5173
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 5173

  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017


networks:
  react-express:
  express-mongo: